### ISSUE TITLE
IndexError with wits.get_tariff_reported

### ISSUE THREAD

**Issue by ethai98** [mwouts/world_trade_data#3] opened 2022-08-04 20:06 UTC
Hello,

I'm getting an IndexError with the following line(s) of code:
`wits.get_tariff_reported(reporter='840',partner='124',product='all',year='2012')` OR
`wits.get_tariff_reported(reporter='840',partner='124',product='all',year='2012', name_or_id = 'id')` 

The output says, "IndexError: list index out of range."

Could you assist with this issue?

Thanks in advance - Eric

**Comment by mwouts** [comment] 2022-08-08 22:33
Hi Eric, thank you for reporting this. I can reproduce the error, I will have a look in the coming days.

**Comment by mwouts** [comment] 2022-08-09 15:11
Hi Eric, I did found a comment about this in the code, and apparently the corresponding switch was not effective. This might be fixed by the PR #4. Would you mind giving a try at the corresponding version with this?
```
pip install git+https://github.com/mwouts/world_trade_data.git@fix_tariffs
```
Keep me posted!

**Comment by ethai98** [comment] 2022-08-09 21:44
Hi! Thank you so much for the quick turnaround. I tried installing the updated version, but I received the following error and warning. Am I doing something wrong when trying to install it via terminal? I also tried pip3.

`Collecting git+https://github.com/mwouts/world_trade_data.git@fix_tariffs
  Cloning https://github.com/mwouts/world_trade_data.git (to revision fix_tariffs) to /private/var/folders/f6/f2w870gj0cz4nt9zj07trhg00000gn/T/pip-req-build-z0io77g8
  Running command git clone -q https://github.com/mwouts/world_trade_data.git /private/var/folders/f6/f2w870gj0cz4nt9zj07trhg00000gn/T/pip-req-build-z0io77g8
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
WARNING: Discarding git+https://github.com/mwouts/world_trade_data.git@fix_tariffs. Command errored out with exit status 1: git clone -q https://github.com/mwouts/world_trade_data.git /private/var/folders/f6/f2w870gj0cz4nt9zj07trhg00000gn/T/pip-req-build-z0io77g8 Check the logs for full command output.
ERROR: Command errored out with exit status 1: git clone -q https://github.com/mwouts/world_trade_data.git /private/var/folders/f6/f2w870gj0cz4nt9zj07trhg00000gn/T/pip-req-build-z0io77g8 Check the logs for full command output.`

**Comment by mwouts** [comment] 2022-08-10 11:40
Hi Eric, thanks for giving it a try. I have no idea why the above did not work on your end, but if you like you can try it on https://colab.research.google.com (see example below).

By the way I am considering another implementation of the same fix, that would consist in returning a `Rate` rather than a `Value` when `get_tariff_*` are called. That would be more consistent with the original attempt, but will require some adaptations in your notebooks since the columns of the dataframes change slightly (The 'Value' column becomes 'Rate'). You can test it with
```
pip install git+https://github.com/mwouts/world_trade_data.git@get_tariff_returns_rate
```
(see for instance [this notebook](https://colab.research.google.com/drive/11cDsCLARFZsETw3bDTq6UbT8RqSjp5JO?usp=sharing) on colab)

Tell me what you think!

**Comment by ethai98** [comment] 2022-08-10 17:54
Hi Marc,

The colab notebook works! Interestingly, the same pip install code does not work on jupyter notebook. 

This is not an error, but something interesting I found from playing around with the code. The reporter-partner combination only yields results if the two countries have a preferential trade agreement (PTA). Otherwise, all other tariffs to all non-PTA countries are found if one enters "000" in partner. 

Question: I hate to ask for one more favor. But would you be able to retrieve the HS6 code from the API data? The current results show only the product description. A product code would be extremely helpful to merge with my other data. 

Again, thank you for the quick turnaround. 

Best regards,
Eric

**Comment by mwouts** [comment] 2022-08-10 22:37
Hi Eric,

> The colab notebook works! Interestingly, the same pip install code does not work on jupyter notebook.

Well, the `pip install` command in the notebook does the same as the local command, so I am not surprised that it fails on your end... Anyway I will soon package a new version and hopefully you will be able to install it from pypi.

> This is not an error, but something interesting I found from playing around with the code. The reporter-partner combination only yields results if the two countries have a preferential trade agreement (PTA). Otherwise, all other tariffs to all non-PTA countries are found if one enters "000" in partner.

Oh that's interesting. Do you think we should add a warning with a mention of this when no result is found?

> Question: I hate to ask for one more favor. But would you be able to retrieve the HS6 code from the API data? The current results show only the product description. A product code would be extremely helpful to merge with my other data.

No problem, I am happy to help (and to improve the package). Is your request covered with `name_or_id='id'`? I mean, 
```
wits.get_tariff_reported(reporter='840',partner='124',product='all',year='2012', name_or_id='id')
```
gives you this:
![image](https://user-images.githubusercontent.com/29915202/184032290-0358cffa-b7fc-472d-9220-fb999f221a9b.png)

But maybe you want ids only for the product (not implemented for now)?

**Comment by ethai98** [comment] 2022-08-11 05:57
Hi Marc,

> Oh that's interesting. Do you think we should add a warning with a mention of this when no result is found?

Yes, I think that would be a good idea to let future users know of this. I think this is characteristic of how WITS store its data.  

> Is your request covered with name_or_id='id'?

Oh, I did not know that part of the code determines whether I receive product code or product name. Could you maybe make that part clearer in the manual for future users? 

Final question: what is the difference between value and rate compared to min_rate and max_rate? I do not see a description for that variable in the WITS API User Manual p.5. Could you help clarify this? Thanks! 

- Edit: I just saw in the last column that it specifies the value as being the SimpleAverage. I'm keeping this question here just in case future users may have the same question!

You have been a great help! Thanks for your quick turnaround on this! Other than my last question above, I think the issue here has been solved!

Best regards,
Eric

**Closed as completed** 2022-08-15 18:25 UTC

**Comment by mwouts** [comment] 2022-08-15 19:04
Thank you Eric. I have added the warning, added a mention of `name_or_id='id'` in the README (and finally reverted the renaming of `Value`). The new release `v0.1.1` will soon be available on pypi.
